spring:
    profiles:
        active: local
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    jpa:
        show-sql: true
        database: postgresql
        properties:
            hibernate:
                format_sql: true
            cache:
                use_second_level_chache: true
                region: factory_class
                generate_statistics: true
            javax:
                persistence:
                    sharedCache:
                        mode: ENABLE_SELECTIVE
    servlet:
      multipart:
          max-file-size: 128MB
          max-request-size: 128MB
          enabled: true
server:
    error:
      path: /error
      include-exception: false
      include-stacktrace: never
      whitelabel:
          enabled: false
      include-binding-errors: never
    port: 8080
logging:
    level:
        root: INFO
        com.example.demo.controller: DEBUG
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE

---
spring:
    config:
        activate:
            on-profile: local
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/sioscmsdb
        username: sioscms
        password: 1q2w3e4r
    jpa:
        hibernate:
            ddl-auto: update
        defer-datasource-initialization: true
        mapping-resources: #application.yml에서는 sql xml파일을 *로 가져올 수 없고, 단일 지정해야함...
            - sqlmap/postgres/orm.xml
            - sqlmap/postgres/menu_sql.xml
    sql:
        init:
            mode: never
    devtools:
        livereload:
            enabled: true
    security:
        user:
            name: admin
            password: 1234
attach:
    path: /Users/sioria/project/sioscms/upload
    delete:
        enabled: true
contents:
    path: /Users/sioria/IdeaProjects/sioscms/src/main/webapp/static/contents
aes:
    secret-key: 01234567890123456789012345678901
    iv-key: 0123456789012345
    spec-name: AES/CBC/PKCS5Padding
---
spring:
    config:
        activate:
            on-profile: dev
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/sioscmsdb
        username: sioscms
        password: 1q2w3e4r
    jpa:
        hibernate:
            ddl-auto: none
        defer-datasource-initialization: true
        mapping-resources: #application.yml에서는 sql xml파일을 *로 가져올 수 없고, 단일 지정해야함...
            - sqlmap/postgres/orm.xml
            - sqlmap/postgres/menu_sql.xml
    sql:
        init:
            mode: never
    devtools:
        livereload:
            enabled: true
    security:
        user:
            name: admin
            password: 1234
attach:
    path: /data/www/xtencms/upload
    delete:
        enabled: true
contents:
    path: /data/www/xtencms/webapps/static/contents
aes:
    secret-key: 01234567890123456789012345678901
    iv-key: 0123456789012345
    spec-name: AES/CBC/PKCS5Padding