spring:
    profiles:
        active: local
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    jpa:
        show-sql: true
        database: postgresql
        properties:
            hibernate:
                format_sql: true
server:
    error:
      path: /error
      include-exception: false
      include-stacktrace: never
      whitelabel:
          enabled: false
      include-binding-errors: never
    port: 8080
logging:
    level:
        root: INFO
        com.example.demo.controller: DEBUG
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE

---
spring:
    profiles:
        active: local
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/sioscmsdb
        username: sioscms
        password: 1q2w3e4r
    jpa:
        hibernate:
            ddl-auto: update
    devtools:
        livereload:
            enabled: true
    security:
        user:
            name: admin
            password: 1234
            
---
spring:
    profiles:
        active: dev
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/sioscmsdb
        username: sioscms
        password: 1q2w3e4r
    jpa:
        hibernate:
            ddl-auto: update
    devtools:
        livereload:
            enabled: true
    security:
        user:
            name: admin
            password: 1234