spring:
    profiles:
        active: local
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    jpa:
        show-sql: true
        database: postgresql
        properties:
            hibernate:
                format_sql: true
            cache:
                use_second_level_chache: true
                region: factory_class
                generate_statistics: true
            javax:
                persistence:
                    sharedCache:
                        mode: ENABLE_SELECTIVE
    servlet:
      multipart:
          max-file-size: 128MB
          max-request-size: 128MB
          enabled: true
server:
    error:
      path: /error
      include-exception: false
      include-stacktrace: never
      whitelabel:
          enabled: false
      include-binding-errors: never
    port: 8080
logging:
    level:
        root: INFO
        com.example.demo.controller: DEBUG
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE

---
spring:
    config:
        activate:
            on-profile: local
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/sioscmsdb
        username: sioscms
        password: 1q2w3e4r
    jpa:
        hibernate:
            ddl-auto: update
    devtools:
        livereload:
            enabled: true
    security:
        user:
            name: admin
            password: 1234
attach:
    path: /Users/sioria/project/sioscms/upload
is-real-file-delete: Y
aes:
    secret-key: dhtkdwnsdi199503291045dhtkdwns12
    iv-key: dhtkdwnsdi199503
    spec-name: AES/CBC/PKCS5Padding
---
spring:
    config:
        activate:
            on-profile: dev
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/sioscmsdb
        username: sioscms
        password: 1q2w3e4r
    jpa:
        hibernate:
            ddl-auto: update
    devtools:
        livereload:
            enabled: true
    security:
        user:
            name: admin
            password: 1234
attach:
    path: /data/www/sioscms/upload
is-real-file-delete: Y
aes:
    secret-key: dhtkdwnsdi199503291045dhtkdwns12
    iv-key: dhtkdwnsdi199503
    spec-name: AES/CBC/PKCS5Padding